---
php_packages:
  - "php{{ php_version }}"
  - "php{{ php_version }}-mysql"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-zip"

# Additional security and configuration for web server
ssh_allowed_users:
  - ansible

firewall_allowed_ports:
  - 80
  - 443
  - 22