---
- hosts: all
  become: yes
  pre_tasks:
    - name: Ensure SSH is installed
      apt:
        name: openssh-server
        state: present

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install essential system packages
      apt:
        name:
          - git
          - curl
          - unzip
          - software-properties-common
          - fail2ban
          - ufw
        state: present

    - name: Configure UFW (Uncomplicated Firewall)
      ufw:
        state: enabled
        policy: deny

    - name: Allow SSH
      ufw:
        rule: allow
        port: ssh

    - name: Allow HTTP and HTTPS
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 80
        - 443