---
- hosts: webservers
  become: yes
  tasks:
    - name: Add PHP repository
      apt_repository:
        repo: "ppa:ondrej/php"
        state: present

    - name: Install Web Server and PHP
      apt:
        name: 
          - "{{ web_server }}"
          - "libapache2-mod-php{{ php_version }}"
          - "{{ php_packages }}"
        state: present
        update_cache: yes

    - name: Enable Apache modules
      apache2_module:
        name: "{{ item }}"
        state: enabled
      loop:
        - rewrite
        - headers
        - ssl

    - name: Create project directory
      file:
        path: "{{ project_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Clone E-commerce Application
      git:
        repo: 'https://github.com/yourusername/ecommerce-webapp.git'
        dest: "{{ project_root }}"
        version: main
      become_user: www-data

    - name: Configure Apache Virtual Host
      template:
        src: ../templates/vhost.conf.j2
        dest: /etc/apache2/sites-available/{{ project_name }}.conf
      notify: Restart Apache

    - name: Enable site
      command: a2ensite {{ project_name }}
      notify: Restart Apache

    - name: Set correct permissions
      file:
        path: "{{ project_root }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

  handlers:
    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted